Updated create-release

diff --git a/bin/create-release b/bin/create-release
--- a/bin/create-release
+++ b/bin/create-release
@@ -13,12 +13,50 @@ fi
 
 cd "$project_dir"
 
-plugin_name=EstimateImport
-name="leantime-plugin-${plugin_name}-${tag}.tar.gz"
+# Configuration start
+
+plugin_name=TimeTable
+# Edit release-exclude.txt to exclude files and folder from release package.
+
+# Configuration end
+
+git config --global --add safe.directory "$PWD"
+if ! git diff --exit-code composer.json; then
+  (>&2 echo; echo composer.json is changed. Aborting.)
+  exit 1
+fi
 
 # Make sure that `composer.json` has the correct version.
 composer config version "${tag}"
-composer install --no-dev
 
-tar --create --file "$name" --exclude-vcs --exclude-from="$script_dir/build-exclude.txt" --transform "s/^\./$plugin_name/" .
+# Build release start
+
+composer install --no-dev --classmap-authoritative
+
+# Build release end
+
+# Package release
+release_dir=release
+target_dir="$release_dir/$plugin_name"
+mkdir -p "$target_dir"
+
+rsync --verbose --archive --compress --filter=':- .gitignore' --exclude-from "$script_dir/release-exclude.txt" . "$target_dir"
+
+# Replace %%VERSION%% with actual version in build
+find ${target_dir} -type f -exec sed -i "s/%%VERSION%%/${tag}/g" {} \;
+
+# Strip any leading `dev-` from tag name in package name.
+name="${plugin_name}-${tag#dev-}.tar.gz"
+tar --create --file "$name" -C "$release_dir" $plugin_name
 sha256sum "$name" >| checksum.txt
+
+# Clean up
+rm -fr $release_dir
+
+git checkout composer.json
+
+echo
+echo "Release content ($name)"
+echo
+tar tvf "$name" | grep -v '/$'
+echo
